version: '3.8'
services:
  app:
    image: php:8.1-fpm
    container_name: encrypted_message_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:80"
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: encrypted_message_db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: messages_db
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
